Repository univelop/yust, pull requests merged in 2024-02, with the labels that each got.

#282 Improve error message
  lib/src/services/yust_database_service_dart.dart
Labels: ✅ Approved

#280 Yust user search tag
  lib/src/models/yust_user.dart
Labels: 🔍 Ready for Review

#279 replace + in name upon sign up
  lib/src/services/yust_auth_service_flutter.dart
Labels: ✅ Approved

#283 Add get google cloud platform method to helper
  lib/src/util/google_cloud_helpers_dart.dart
Labels: ✅ Approved

#284 Improve database service
  lib/src/models/yust_filter.dart
  lib/src/services/yust_auth_service_flutter.dart
  lib/src/services/yust_database_service_dart.dart
  lib/src/services/yust_database_service_flutter.dart
  lib/src/services/yust_database_service_mocked.dart
  lib/src/services/yust_file_service_dart.dart
  lib/src/services/yust_file_service_flutter.dart
  lib/src/util/google_cloud_helpers_dart.dart
  lib/src/util/google_cloud_helpers_flutter.dart
  lib/src/util/google_cloud_helpers_shared.dart
  lib/src/util/yust_exception.dart
  lib/src/yust.dart
  lib/yust.dart
Labels: ✅ Approved

#285 Fix Linter Issues
  lib/src/util/google_cloud_helpers_dart.dart
Labels: 🔍 Ready for Review

#286 2520 Add user locale and locale-based date formatting
  lib/src/models/yust_user.dart
  lib/src/models/yust_user.g.dart
  lib/src/util/yust_helpers.dart
Labels: 🔍 Ready for Review, ✅ Approved

#288 Fix Timezones Initalization
  lib/src/yust.dart
Labels: ✅ Approved

#290 Log file downloads
  lib/src/services/yust_file_service_dart.dart
Labels: ✅ Approved

#292 Better handling of transaction errors
  lib/src/services/yust_database_service_dart.dart
  lib/src/util/yust_exception.dart
Labels: 🔍 Ready for Review
