Repository univelop/yust, pull requests merged in 2024-01, with the labels that each got.

#275 Fix Wrong Function Signature of `runTransactionForDocument`
  lib/src/services/yust_database_service_flutter.dart
  lib/src/services/yust_database_service_mocked.dart
Labels: 🔍 Ready for Review, ✅ Approved

#276 Upgrade Packages
  lib/src/services/yust_database_service_flutter.dart
  pubspec.yaml
Labels: 🔍 Ready for Review

#272 Implement sum and avg
  lib/src/services/yust_database_service_dart.dart
  lib/src/services/yust_database_service_flutter.dart
  lib/src/services/yust_database_service_mocked.dart
Labels: ✅ Approved

#277 Fix function signatures for flutter
  lib/src/services/yust_database_service_flutter.dart
Labels: 🔍 Ready for Review, ✅ Approved

#278 Fix Flutter `YustDatabaseService.getListChunked` for empty results
  lib/src/services/yust_database_service_flutter.dart
Labels: ✅ Approved

#262 set default enums for JsonSerializables
  lib/src/models/yust_filter.dart
  lib/src/models/yust_user.dart
  lib/src/models/yust_user.g.dart
  lib/src/services/yust_auth_service_flutter.dart
  lib/src/services/yust_database_service_flutter.dart
Labels: ✅ Approved

#268 #1661: Allow to change Email, even if AuthMethod is not email
  lib/src/services/yust_auth_service_flutter.dart
Labels: 🔍 Ready for Review

#281 Fix Linter issues
  lib/src/services/yust_auth_service_flutter.dart
  lib/src/util/yust_exception.dart
Labels: ✅ Approved
