Repository univelop/yust, pull requests merged in 2024-04, with the labels that each got.

#300 refactor get list chunked to use cursor
  lib/src/services/yust_database_service_dart.dart
Labels: 🔍 Ready for Review

#301 Improve naming and error message
  lib/src/services/yust_database_service_dart.dart
  lib/src/util/yust_exception.dart
Labels: 🔍 Ready for Review, ✅ Approved

#302 Fix Retry of YustExceptions
  lib/src/services/yust_database_service_dart.dart
Labels: 🔍 Ready for Review

#303 Fix order by clauses on get list chunked
  lib/src/models/yust_filter.dart
  lib/src/services/yust_database_service_dart.dart
Labels: ✅ Approved

#305 Fix saveDoc in Flutter Database Service
  lib/src/services/yust_database_service_flutter.dart
Labels: ✅ Approved

#306 Add LastLoginDomain
  lib/src/models/yust_user.dart
  lib/src/services/yust_auth_service_flutter.dart
Labels: 🔍 Ready for Review

#309 Escape also OrderBy fields
  lib/src/services/yust_database_service_dart.dart
  lib/src/util/yust_helpers.dart
Labels: 🔍 Ready for Review

#307 Catch Permission Errors on FlutterDatabaseService.Get
  lib/src/services/yust_database_service_flutter.dart
Labels: 🔍 Ready for Review

#308 Improve DatabaseStatistics
  lib/src/services/yust_database_service_dart.dart
  lib/src/services/yust_database_service_flutter.dart
  lib/src/util/yust_database_statistics.dart
  lib/src/util/yust_query_with_logging.dart
  lib/src/yust.dart
Labels: 🔍 Ready for Review

#310 Small Fixes
  lib/src/util/google_cloud_helpers_flutter.dart
  lib/src/util/yust_query_with_logging.dart
  lib/src/yust.dart
  pubspec.yaml
Labels: 🔍 Ready for Review

#312 #3110 using DeepCollectionEquality to compare lists properly too
  lib/src/models/yust_filter.dart
Labels: 🔍 Ready for Review
